#!/usr/bin/env bash

CDK_LOG_LEVEL=INFO
CDK_REGION=us-east-1
CDK_PFIX=cmdfw
CDK_ENV=prod2
CDK_ORG=cmdfw
CDK_CONFIG_PATH="${CMDFW_CDK_CONFIG_PATH}"
FEDERATE_JKS_PATH="${CMDFW_JKS_PATH}"
FEDERATE_STORE_PWD="${CMDFW_SP}"
FEDERATE_KEY_PWD="${CMDFW_KP}"
FEDERATE_AWS_PROP="${CMDFW_AWS_PROP}"

